# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_graduacao = QtWidgets.QComboBox(self.centralwidget)
        self.cb_graduacao.setGeometry(QtCore.QRect(200, 120, 241, 31))
        self.cb_graduacao.setObjectName("cb_graduacao")
        self.cb_graduacao.addItem("")
        self.cb_graduacao.addItem("")
        self.cb_graduacao.addItem("")
        self.cb_graduacao.addItem("")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(200, 230, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.ck_manha = QtWidgets.QCheckBox(self.centralwidget)
        self.ck_manha.setGeometry(QtCore.QRect(200, 180, 70, 17))
        self.ck_manha.setStyleSheet("border: rgb(0, 0, 255)")
        self.ck_manha.setObjectName("ck_manha")
        self.lb_nome = QtWidgets.QLabel(self.centralwidget)
        self.lb_nome.setGeometry(QtCore.QRect(113, 74, 71, 31))
        self.lb_nome.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_nome.setObjectName("lb_nome")
        self.lb_graduacao = QtWidgets.QLabel(self.centralwidget)
        self.lb_graduacao.setGeometry(QtCore.QRect(60, 120, 131, 31))
        self.lb_graduacao.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_graduacao.setObjectName("lb_graduacao")
        self.txt_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nome.setGeometry(QtCore.QRect(200, 77, 351, 31))
        self.txt_nome.setObjectName("txt_nome")
        self.lb_disponibilidade = QtWidgets.QLabel(self.centralwidget)
        self.lb_disponibilidade.setGeometry(QtCore.QRect(15, 170, 181, 31))
        self.lb_disponibilidade.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_disponibilidade.setObjectName("lb_disponibilidade")
        self.lb_area = QtWidgets.QLabel(self.centralwidget)
        self.lb_area.setGeometry(QtCore.QRect(126, 220, 61, 31))
        self.lb_area.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_area.setObjectName("lb_area")
        self.ck_tarde = QtWidgets.QCheckBox(self.centralwidget)
        self.ck_tarde.setGeometry(QtCore.QRect(280, 180, 70, 17))
        self.ck_tarde.setObjectName("ck_tarde")
        self.ck_noite = QtWidgets.QCheckBox(self.centralwidget)
        self.ck_noite.setGeometry(QtCore.QRect(354, 180, 70, 17))
        self.ck_noite.setObjectName("ck_noite")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(260, 230, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(340, 230, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(420, 230, 101, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 300, 151, 61))
        self.pushButton.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 255);\n"
"background: #03fc90;\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb_graduacao.setItemText(0, _translate("MainWindow", "Em conclusão"))
        self.cb_graduacao.setItemText(1, _translate("MainWindow", "Completa"))
        self.cb_graduacao.setItemText(2, _translate("MainWindow", "Pós-graduação incompleta"))
        self.cb_graduacao.setItemText(3, _translate("MainWindow", "Pós-graduação completa"))
        self.radioButton.setText(_translate("MainWindow", "Teste"))
        self.ck_manha.setText(_translate("MainWindow", "Manhã"))
        self.lb_nome.setText(_translate("MainWindow", "Nome:"))
        self.lb_graduacao.setText(_translate("MainWindow", "Graduação:"))
        self.lb_disponibilidade.setText(_translate("MainWindow", "Disponibilidade:"))
        self.lb_area.setText(_translate("MainWindow", "Área:"))
        self.ck_tarde.setText(_translate("MainWindow", "Tarde"))
        self.ck_noite.setText(_translate("MainWindow", "Noite"))
        self.radioButton_2.setText(_translate("MainWindow", "Qualidade"))
        self.radioButton_3.setText(_translate("MainWindow", "Produção"))
        self.radioButton_4.setText(_translate("MainWindow", "Documentação"))
        self.pushButton.setText(_translate("MainWindow", "Inscrever-se"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
